### ISSUE TITLE
[Bug]: CSS: Navbar bg color in Firefox is too transparent

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/explorer#131]
### Issue description

The bg color of the navbar in Firefox (because firefox is not compatible with the CSS effect applied) imo is too transparent and doesnt look good on scroll

![image](https://user-images.githubusercontent.com/3624944/153270947-1611dfd6-0a39-4b0e-a86e-6512c7938038.png)
![image](https://user-images.githubusercontent.com/3624944/153271445-9ca0304a-c057-46ae-b8a0-d25463c6cc95.png)

### Expected behaviour

I would personally increase the opacities:

eg:
![image](https://user-images.githubusercontent.com/3624944/153271112-450bdf2b-a35e-4cbb-8244-5c0dd7d8a7eb.png)
![image](https://user-images.githubusercontent.com/3624944/153271219-45be9257-bb5d-4798-8c81-f07f4c3dbbb7.png)

### Actual behaviour

Too transparent and to me looks like a bug 🐛 

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Open the staging explorer on firefox
2. Scroll so content overlaps the navbar

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by r-c-k** [comment]
Same with [iota.org](https://iota.org), [shimmer.network](https://shimmer.network) and [assembly.sc](https://assembly.sc).
Also, while the background of the navbar at `iota.org` is translucent under Safari, it is very subtle and almost unnoticeable - maybe it could be adapted to match the other nav bars.

(I hope it's ok to mention this issue here)

**Comment by laumair** [comment]
Fixed in https://github.com/iotaledger/explorer/pull/153
