### ISSUE TITLE
[Bug]: It is not clear what messages per second is indicator on landing page

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/explorer#146]
### Issue description

As there are two sides to the messages per second it is not clear what each side is representing.i.e. 
11.2/11.3 what does this mean?

### Expected behaviour

Only one value below each header. Or sub header is added to each part. Or information icon is used.

### Actual behaviour

Unclear what it represents.

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laumair** [comment]
Should be discussed with UI / UX team.

**Comment by laumair** [comment]
We should probably have a space between <value> / <value>. The text could be changed to `Messages / Confirmations (per second)`

**Comment by laumair** [comment]
After having an internal discussion, `confirmations per second` don't make a lot of sense because the milestone is every second. Plus, confirmation rate can never be higher than the messages rate so the statistic itself is wrong. 

We should only display `Messages per second` and the label should also just reflect that.
