### ISSUE TITLE
[Task]: Truncate Ids but keep them findable with CTRL+F

### ISSUE THREAD

**Issue by msarcev** [iotaledger/explorer#587]
### Task description

- Come up with a solution so that truncated Ids (with dots in the middle) can still be found with CTRL+F browser function, and make a generic component for that logic.
- Add it too:
    - Landing page - Milestone Feed (stardust)
    - Address page (all sections) (stardust)

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by abbasabid** [comment]
In order to make the truncated ids findable with CTRL-F we have used `text-overflow: ellipsis` and give a specific `width` to first span and concat it with the second span which has last ten characters of the id. When a user search the id with CTRL-F on a browser the first span will be highlighted. The only problem here is if someone changes the css of truncated-id to have more width, it will start showing letters from the second part in the first part potentially. Right now we are not able to find any better solution than this which require less effort.

Alternatively, one thing which we can do is we can only display a single span which have the truncated id and will be displayed like this `0xasdadasd…`.
